### ISSUE TITLE
Can’t upgrade to 11.3. 

### ISSUE THREAD

**Issue by ejh4286** [revunix/GIGABYTE-X399-Designare-EX#1]
Can’t upgrade to 11.3. Installation hangs with Apple logo after running the initial “Install MacOS Big Sur”. The open core menu gives me an option to boot to 11.2, which still works. Any thoughts

**Comment by revunix** [comment]
did you tried to update the AMD Patches?
https://github.com/AMD-OSX/AMD_Vanilla/blob/opencore/17h_19h/patches.plist

**Comment by ejh4286** [comment]
I did, but that exceeds my config.plist editing knowledge.  I guess I’m out of luck for the time being.
